### PR TITLE
[GH-263] Fix tier up

### LINKED ISSUE #263: Tier Up button is not showing up on level 20 units
- Implement showing tier up button instead of level up button when the unit reaches the maximum level for the tier
- Implement blocking the tier up button when the unit is in the maximum tier of the rank

### PR DESCRIPTION
**Pull request by ncontinanza**
Closes #263 

## Motivation

We weren't able to tier up our units once the max level of a tier was reached.

## Summary of changes

Add a tier up pop up with a button that allows tiering up the unit. Also, once the max tier of a rank has been reached, an error pop up is shown.

## How has this been tested?

1. Start the backend and add currency to your user by running: `GameBackend.Users.Currencies.add_currency_by_name_and_game!(user_id, "Gold", 2, 2000000)`
2. Go to the barracks and pick the unit you'll level up.
3. Level your unit up to level 20 and, when trying to level it up once more, make sure that you see the tier up pop up. 
4. Use the tier up button, and now you should be able to level up your unit once more. Check that the correct level is shown in the screen, and that the level up costs are being properly updated across this process.
5. Continue leveling and tiering up until you reach the max level of the max tier. When you try to tier up, you should now see an error pop up telling you that you must rank up your unit.

## Checklist
- [X] I have tested the changes locally.
- [X] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by lotuuu — CHANGES_REQUESTED** [review]
Works great! Let's also display:
1. tier up cost in pop up.
2. tier next to the level or somewhere in the unit scene.

Also, why did you choose to do this as a pop up instead of automatically changing the "level up" button to "tier up"? If the idea is to do it like this because it's faster as a first iteration, I'm on board. If it was by design, I'm not a fan of it

**Comment by ncontinanza** [comment]
> Works great! Let's also display:
> 
> 1. tier up cost in pop up.
> 2. tier next to the level or somewhere in the unit scene.
> 
> Also, why did you choose to do this as a pop up instead of automatically changing the "level up" button to "tier up"? If the idea is to do it like this because it's faster as a first iteration, I'm on board. If it was by design, I'm not a fan of it

Great, I added the cost to the pop up, and the unit's tear right below the level.
About the pop up vs changing the button discussion, what do you think of iterating on that once we have a UI design for this?

**Review by lotuuu — APPROVED** [review]
Yes, let's iterate! Please create the issues so we don't lose track of this!

**Review by tkz00 — APPROVED** [review]
Screenshot 2024-06-07 at 12 23 13 PM
Screenshot 2024-06-07 at 12 24 15 PM

This is a problem not introduced by these changes, but made visible by them, since we aren't handling aesthetics at this stage, I've added this issue to tackle latter: [Costs in Unit Detail screen jump line](https://github.com/lambdaclass/afk_gacha_game/issues/484).

**Pull request merged**
